<?php

/*
CRIAR A INTERFACE AREACALCULAVEL COM O MÉTODO CALCULAAREA() - SEM
PARÂMETROS E QUE RETORNA UM DOUBLE
CRIAR ALGUMAS CLASSES QUE IMPLEMENTAM AREACALCULAVEL:

QUADRADO: POSSUI UM ATRIBUTO LADO
RETANGULO: POSSUI OS ATRIBUTOS BASE E ALTURA
CIRCULO: POSSUI O ATRIBUTO RAIO
*/

interface AreaCalculavel  {

    public function CalculaArea(){
        
    }

} 
?>